Repository backendINFJ/b4-trello, pull requests merged in 2024-07, with the labels that each got.

#49 보드 리팩토링
  .gitignore
  build.gradle
  src/main/java/com/nbcamp/b4trello/config/PropertyConfig.java
  src/main/java/com/nbcamp/b4trello/controller/BoardController.java
  src/main/java/com/nbcamp/b4trello/controller/UserController.java
  src/main/java/com/nbcamp/b4trello/dto/BoardRequestDto.java
  src/main/java/com/nbcamp/b4trello/dto/BoardResponseDto.java
  src/main/java/com/nbcamp/b4trello/dto/ErrorMessageEnum.java
  src/main/java/com/nbcamp/b4trello/dto/ResponseEnum.java
  src/main/java/com/nbcamp/b4trello/entity/Board.java
  src/main/java/com/nbcamp/b4trello/entity/UserBoard.java
  src/main/java/com/nbcamp/b4trello/entity/UserType.java
  src/main/java/com/nbcamp/b4trello/repository/BoardRepository.java
  src/main/java/com/nbcamp/b4trello/repository/UserBoardRepository.java
  src/main/java/com/nbcamp/b4trello/service/BoardService.java
Labels: refactor

#45 보드에 다른 사용자 초대
  build.gradle
  src/main/java/com/nbcamp/b4trello/controller/BoardController.java
  src/main/java/com/nbcamp/b4trello/dto/BoardRequestDto.java
  src/main/java/com/nbcamp/b4trello/dto/BoardResponseDto.java
  src/main/java/com/nbcamp/b4trello/dto/ErrorMessageEnum.java
  src/main/java/com/nbcamp/b4trello/dto/ResponseEnum.java
  src/main/java/com/nbcamp/b4trello/entity/Board.java
  src/main/java/com/nbcamp/b4trello/entity/UserBoard.java
  src/main/java/com/nbcamp/b4trello/entity/UserType.java
  src/main/java/com/nbcamp/b4trello/repository/BoardRepository.java
  src/main/java/com/nbcamp/b4trello/repository/UserBoardRepository.java
  src/main/java/com/nbcamp/b4trello/repository/UserRepository.java
  src/main/java/com/nbcamp/b4trello/service/BoardService.java
  src/main/java/com/nbcamp/b4trello/service/UserService.java
Labels: feature

#58 refacotr : ResponseEnum 중복제거, SecurityConfig 인가, Board관련 오류해결
  build/classes/java/main/com/nbcamp/b4trello/config/SecurityConfig.class
  src/main/java/com/nbcamp/b4trello/config/SecurityConfig.java
  src/main/java/com/nbcamp/b4trello/controller/UserController.java
  src/main/java/com/nbcamp/b4trello/dto/ResponseEnum.java
  src/main/java/com/nbcamp/b4trello/dto/UserRequestDto.java
  src/main/java/com/nbcamp/b4trello/repository/BoardRepository.java
  src/main/java/com/nbcamp/b4trello/repository/UserBoardRepository.java
  src/main/java/com/nbcamp/b4trello/service/BoardService.java
Labels: refactor

#59 refacotr : Board CRUD + 초대 기능테스트 완료
  build/classes/java/main/com/nbcamp/b4trello/dto/ErrorMessageDTO.class
  build/classes/java/main/com/nbcamp/b4trello/dto/ResponseEnum.class
  src/main/java/com/nbcamp/b4trello/controller/BoardController.java
  src/main/java/com/nbcamp/b4trello/dto/BoardInviationRequestDto.java
  src/main/java/com/nbcamp/b4trello/dto/BoardInviationResponseDto.java
  src/main/java/com/nbcamp/b4trello/repository/UserBoardRepository.java
  src/main/java/com/nbcamp/b4trello/service/BoardService.java
Labels: refactor

#60 17 card crud
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  build/classes/java/main/com/nbcamp/b4trello/config/SecurityConfig.class
  build/classes/java/main/com/nbcamp/b4trello/controller/AuthController.class
  build/classes/java/main/com/nbcamp/b4trello/controller/UserController.class
  build/classes/java/main/com/nbcamp/b4trello/dto/AuthRequestDTO.class
  build/classes/java/main/com/nbcamp/b4trello/dto/CommonResponse.class
  build/classes/java/main/com/nbcamp/b4trello/dto/ErrorMessageEnum.class
  build/classes/java/main/com/nbcamp/b4trello/dto/ResponseEnum.class
  build/classes/java/main/com/nbcamp/b4trello/dto/UserRequestDTO.class
  build/classes/java/main/com/nbcamp/b4trello/entity/Card.class
  build/classes/java/main/com/nbcamp/b4trello/entity/RefreshToken.class
  build/classes/java/main/com/nbcamp/b4trello/entity/User.class
  build/classes/java/main/com/nbcamp/b4trello/enums/StatusEnum.class
  build/classes/java/main/com/nbcamp/b4trello/exception/GlobalExceptionHandler.class
  build/classes/java/main/com/nbcamp/b4trello/jwt/JwtAuthenticationFilter.class
  build/classes/java/main/com/nbcamp/b4trello/service/AuthService.class
  build/classes/java/main/com/nbcamp/b4trello/service/UserService.class
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/generated/com/nbcamp/b4trello/entity/QBoard.java
  src/main/generated/com/nbcamp/b4trello/entity/QCard.java
  src/main/generated/com/nbcamp/b4trello/entity/QColumns.java
  src/main/generated/com/nbcamp/b4trello/entity/QComment.java
  src/main/generated/com/nbcamp/b4trello/entity/QRefreshToken.java
  src/main/generated/com/nbcamp/b4trello/entity/QTimestamped.java
  src/main/generated/com/nbcamp/b4trello/entity/QUser.java
  src/main/generated/com/nbcamp/b4trello/entity/QUserBoard.java
  src/main/java/com/nbcamp/b4trello/config/QueryDslConfiguration.java
  src/main/java/com/nbcamp/b4trello/controller/CardController.java
  src/main/java/com/nbcamp/b4trello/dto/CardListResponseDto.java
  src/main/java/com/nbcamp/b4trello/dto/CardRequestDto.java
  src/main/java/com/nbcamp/b4trello/dto/CardResponseDto.java
  src/main/java/com/nbcamp/b4trello/dto/CardUpdateRequestDto.java
  src/main/java/com/nbcamp/b4trello/dto/CommonResponse.java
  src/main/java/com/nbcamp/b4trello/dto/ErrorMessageEnum.java
  src/main/java/com/nbcamp/b4trello/dto/ResponseEnum.java
  src/main/java/com/nbcamp/b4trello/entity/Card.java
  src/main/java/com/nbcamp/b4trello/entity/CardStatus.java
  src/main/java/com/nbcamp/b4trello/repository/CardDslRepository.java
  src/main/java/com/nbcamp/b4trello/repository/CardRepository.java
  src/main/java/com/nbcamp/b4trello/service/CardService.java
Labels: enhancement

#71 refactor : 보드 초대시 기존에 이메일 인증된 사람만 초대가 가능하게 기능수정
  src/main/java/com/nbcamp/b4trello/controller/BoardController.java
  src/main/java/com/nbcamp/b4trello/dto/ErrorMessageEnum.java
  src/main/java/com/nbcamp/b4trello/enums/StatusEnum.java
  src/main/java/com/nbcamp/b4trello/service/BoardService.java
Labels: refactor
